$(function(){
    var $main=$('#main');
    var $menu=$(''
        +'<div class="a">'
		+'<ul>'
			+'<li>'
                +'<a href="" >文件(F)</a>'           
                +'<ul>'
                    +'<li>'
                        +'<div class="xiao">'
                            +'<a href="">新建(N)</a>'
                            +'<a href="" class="xa">Ctrl+N</a>'
                        +'</div>'                     
                    +'</li>'
                    +'<li><div class="xiao">'
                        +'<a href="">打开</a>'
                        +'<a href="" class="xa">Ctrl+O</a>'
                    +'</div></li>'
                    +'<li>'
                    +'<div>'
                        +'<a href="">保存</a>'
                        +'<a href="" class="xa">Ctrl+S</a>'
                    +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                        +'<a href="">另保存</a>'
                    +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                        +'<a href="">页面设置</a>'
                    +'</div>'
                    +'</li>'
                    +'<li>'
                    +'<div>'
                        +'<a href="">打印</a>'
                    +'</div>'
                    +'</li>'
                    +'<li>'
                    +'<div>'
                        +'<a href="">退出</a>'
                    +'</div>'
                    +'</li>'
                +'</ul>'
            +'</li>'
			+'<li>'
				+'<a href="">编辑(E)</a>'
				+'<ul>'
					+'<li>'
                        +'<div>'
                            +'<a href="">撤销(U)</a>'
                            +'<a href="" class="xa">Ctrl+Z</a>'
                       +'</div>'
                    +'</li>'
					+'<li>'
                        +'<div>'
                            +'<a href="">剪切(T)</a>'
                            +'<a href="" class="xa">Ctrl+X</a>'
                        +'</div>'
                    +'</li>'
					+'<li>'
                        +'<div>'
                            +'<a href="">复制(css)</a>'
                            +'<a href="" class="xa">Ctrl+C</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">粘贴(P)</a>'
                            +'<a href="" class="xa">Ctrl+V</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">删除(L)</a>'
                            +'<a href="" class="xa">del</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                           +'<a href="">使用bing搜索</a>'
                            +'<a href="" class="xa">Ctrl+E</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">查找(F)</a>'
                            +'<a href="" class="xa">Ctrl+F</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">查找下一个(N)</a>'
                            +'<a href="" class="xa">F3</a>'
                        +'</div>'
                    +'</li>'
                   +'<li>'
                        +'<div>'
                            +'<a href="">替换(R)</a>'
                            +'<a href="" class="xa">Ctrl+H</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">转到(G)</a>'
                            +'<a href="" class="xa">Ctrl+G</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">全选(A)</a>'
                            +'<a href="" class="xa">Ctrl+A</a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">时间/日期(D)</a>'
                            +'<a href="" class="xa">F3</a>'
                        +'</div>'
                    +'</li>'
				+'</ul>'
			+'</li>'
			+'<li>'
				+'<a href="">格式(O)</a>'
				+'<ul>'
					+'<li>'
                        +'<div>'
                        +'<a href="">自动换行(W)</a>'
                    +'</div>'
                    +'</li>'
					+'<li id="fonts">'
                        +'<div>字体</div>'
                    +'</li>'
				+'</ul>'
			+'</li>'
			+'<li>'
				+'<a href="">查看(V)</a>'
				+'<ul>'
					+'<li>'
                        +'<div>'
                            +'<a href="">状态栏(S)</a>'
                            +'<a href="" class="xa"></a>'
                        +'</div>'
                    +'</li>'
				+'</ul>'
			+'</li>'
            +'<li>'
                +'<a href="">帮助(H)</a>'
               +'<ul>'
					+'<li>'
                        +'<div>'
                            +'<a href="">查看帮助(S)</a>'
                            +'<a href="" class="xa"></a>'
                        +'</div>'
                    +'</li>'
                    +'<li>'
                        +'<div>'
                            +'<a href="">关于记事本(A)</a>'
                        +'</div>'
                    +'</li>'
				+'</ul>'
            +'</li>'
        +'</ul>'
        +'<div>'
            +'<textarea name="" id="" cols="130" rows="30" style="font-size: 20px;"></textarea>'
        +'</div>'
    +'</div>'
    );
    $main.append($menu);
    var $fonts=$('#fonts');
    $fonts.click(function(){
        $font.show();
    })
})